@echo off
echo Starting PathOS Backend Server (Port 8002)...
echo Changing directory to backend...
cd backend
echo Using virtual environment...
call venv\Scripts\uvicorn main:app --reload --port 8002
pause